### PR TITLE
Removed required attributes in Address.cs  save points 00-04

### PR DESCRIPTION
**Pull request by surayya-MS**
Session 2 will not work when following guide.
https://github.com/dotnet-presentations/blazor-workshop/issues/339

### CODE REVIEW

**Comment by jongalloway** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/dotnet-presentations/blazor-workshop?pullRequest=354) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet-presentations/blazor-workshop?pullRequest=354) before we can accept your contribution.<br/><br/>:x: surayya-MS [sign now](https://cla.dotnetfoundation.org/dotnet-presentations/blazor-workshop?pullRequest=354)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet-presentations/blazor-workshop?pullRequest=354) it.</sub>

**Comment by javiercn** [comment]
@danroth27 can you look at this and merge it if you are ok with it?

**Comment by danroth27** [comment]
Instead of commenting out the validation attributes, can we just remove them?

**Comment by csharpfritz** [comment]
I agree with Dan... in these earlier modules of the workshop, let's delete the attributes

**Comment by surayya-MS** [comment]
Deleted required attributes in Address.cs savepoints 00-04. Required atributes appear in session 5

**Review by danroth27 — APPROVED** [review]
:shipit:

**Pull request merged**
