### PR TITLE
Migrated to net5.0 TFM

### PR DESCRIPTION
**Pull request by mkArtakMSFT**

### CODE REVIEW

**Comment by SteveSandersonMS** [comment]
Thanks @mkArtakMSFT! The changes looks good. I'm glad this is a pretty simple upgrade.

We won't be able to merge this into `master` until .NET 5 ships, because people are still using this repo for 3.2.0. Would you be able to retarget the PR to a different branch, e.g., called `net5`?

Longer term when we want to merge this to `master` then it would also be necessary to update all the code snapshots in the `save-points` directory. I totally understand you might not want to do that right now if the goal is just to have a finished sample for size measurements.

**Comment by mkArtakMSFT** [comment]
Was talking to @danroth27 about this and he has suggested to have a new branch in this repo for 5.0. @SteveSandersonMS what are your thoughts? Can you create that new branch and I can retarget this PR to that?

**Comment by mkArtakMSFT** [comment]
Merging into the release/5.0 branch as is. We can make changes afterwards as needed.

**Comment by mkArtakMSFT** [comment]
@danroth27  FYI

**Pull request merged**
