### PR TITLE
Update Order.cs

### PR DESCRIPTION
**Pull request by GutierrezDev**
Fix DeliveryLocation bein null when converting to MapMarker.

### CODE REVIEW

**Comment by GutierrezDev** [comment]
The DeliveryLocation object is not initialized so trying to create a MapMarker throws exception.

**Comment by rynowak** [comment]
Sorry, it's been a while and no one's looked at this PR - do you remember what happened to cause this problem? I'm not sure a blank LatLong object is more correct.

**Comment by yopez83** [comment]
> Sorry, it's been a while and no one's looked at this PR - do you remember what happened to cause this problem? I'm not sure a blank LatLong object is more correct.

I don't think this should be a problem today, since the `PlaceOrder` endpoint from `OrdersController.cs` at line 62 initializes the LatLong property. `order.DeliveryLocation = new LatLong(51.5001, -0.1239);`

**Comment by danroth27** [comment]
Closing as it sounds like this is no longer needed.

**Pull request closed without merging**
